site_name: Librarika Manual (Beta)
repo_url: https://github.com/Librarika/manual.git
repo_name: GitHub
site_description: The free integrated library system - ILS 
site_author: Librarika Team
theme:
    name: 'material'
    logo: 'img/logo-tr.png'
    favicon: 'img/logo.png'
markdown_extensions:
  - admonition
extra_css:
  - 'css/extra.css'
nav:
    - 'Home': 'index.md'
    - 'User Guide': 
      - 'Getting Started': 'getting-started.md'
      - 'OPAC': 'opacs.md'
      - 'Library': 'libraries.md'
      - 'Cataloging (Books)': 'cataloging.md'
      - 'Members (Patrons)': 'members.md'
      - 'Circulations (Loans)': 'circulations.md'
      - 'Fees & Payments': 'fees-payments.md'
      - 'Barcode Labels': 'barcode-labels.md'
      - 'Reports': 'reports.md'
      - 'Member Area': 'member-area.md'
      - 'Users': 'users.md'
      - 'Bulk Actions': 'bulk-actions.md'
      - 'Batch Update': 'batch-update.md'
    - 'Contributing': 'contribute.md'
    - 'About': 'about.md'
    - 'License': 'license.md'