site_name: Librarika Manual (Alpha)
repo_url: https://github.com/Librarika/manual.git
repo_name: GitHub
site_description: The free integrated library system - ILS 
site_author: Librarika Team
theme: readthedocs
pages:
    - 'Home': 'index.md'
    - 'User Guide': 
      - 'Getting Started': 'getting-started.md'
      - 'Library': 'libraries.md'
      - 'Cataloging (Books)': 'cataloging.md'
      - 'Members (Patrons)': 'members.md'
      - 'Circulations (Loans)': 'circulations.md'
#      - 'Users': 'users.md'
#      - 'Barcode Labels': 'barcode-labels.md'
#      - 'Bulk Actions': 'bulk-actions.md'
    - 'Contributing': 'contribute.md'
    - 'About': 'about.md'